// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_gain = "CgkI8oCBp5kNEAIQGA"; // <GPGSID>
        public const string achievement_follow_heart = "CgkI8oCBp5kNEAIQIA"; // <GPGSID>
        public const string achievement_10_mins_today = "CgkI8oCBp5kNEAIQAg"; // <GPGSID>
        public const string leaderboard_gold = "CgkI8oCBp5kNEAIQKA"; // <GPGSID>
        public const string achievement_newbie_of_fight = "CgkI8oCBp5kNEAIQCg"; // <GPGSID>
        public const string leaderboard_challenge_mode_wins = "CgkI8oCBp5kNEAIQJA"; // <GPGSID>
        public const string achievement_surprise = "CgkI8oCBp5kNEAIQGQ"; // <GPGSID>
        public const string achievement_fighter_lover = "CgkI8oCBp5kNEAIQDg"; // <GPGSID>
        public const string achievement_60_min_today = "CgkI8oCBp5kNEAIQBA"; // <GPGSID>
        public const string achievement_good_start = "CgkI8oCBp5kNEAIQFg"; // <GPGSID>
        public const string achievement_r_u_disabled = "CgkI8oCBp5kNEAIQFA"; // <GPGSID>
        public const string achievement_no_one = "CgkI8oCBp5kNEAIQIw"; // <GPGSID>
        public const string achievement_no_desire = "CgkI8oCBp5kNEAIQHQ"; // <GPGSID>
        public const string achievement_fans_of_fight = "CgkI8oCBp5kNEAIQCw"; // <GPGSID>
        public const string achievement_excellent = "CgkI8oCBp5kNEAIQCA"; // <GPGSID>
        public const string achievement_strong = "CgkI8oCBp5kNEAIQDQ"; // <GPGSID>
        public const string leaderboard_story_mode_wins = "CgkI8oCBp5kNEAIQJQ"; // <GPGSID>
        public const string achievement_great_collector = "CgkI8oCBp5kNEAIQEg"; // <GPGSID>
        public const string achievement_transparent = "CgkI8oCBp5kNEAIQIg"; // <GPGSID>
        public const string achievement_legendary = "CgkI8oCBp5kNEAIQEA"; // <GPGSID>
        public const string achievement_aspirant = "CgkI8oCBp5kNEAIQDw"; // <GPGSID>
        public const string achievement_richer = "CgkI8oCBp5kNEAIQHA"; // <GPGSID>
        public const string leaderboard_gems = "CgkI8oCBp5kNEAIQKQ"; // <GPGSID>
        public const string achievement_marvellous = "CgkI8oCBp5kNEAIQCQ"; // <GPGSID>
        public const string achievement_new_fighter = "CgkI8oCBp5kNEAIQAQ"; // <GPGSID>
        public const string leaderboard_perfect_wins = "CgkI8oCBp5kNEAIQJw"; // <GPGSID>
        public const string achievement_harvest = "CgkI8oCBp5kNEAIQGg"; // <GPGSID>
        public const string achievement_legend_of_fight = "CgkI8oCBp5kNEAIQDA"; // <GPGSID>
        public const string achievement_alms = "CgkI8oCBp5kNEAIQHg"; // <GPGSID>
        public const string achievement_r_u_ok = "CgkI8oCBp5kNEAIQEw"; // <GPGSID>
        public const string achievement_r_u_dead = "CgkI8oCBp5kNEAIQFQ"; // <GPGSID>
        public const string leaderboard_multiplayer_mode_wins = "CgkI8oCBp5kNEAIQJg"; // <GPGSID>
        public const string achievement_30_min_today = "CgkI8oCBp5kNEAIQAw"; // <GPGSID>
        public const string achievement_millionaire = "CgkI8oCBp5kNEAIQBg"; // <GPGSID>
        public const string achievement_good_game = "CgkI8oCBp5kNEAIQFw"; // <GPGSID>
        public const string achievement_true_fans = "CgkI8oCBp5kNEAIQEQ"; // <GPGSID>
        public const string achievement_wealth = "CgkI8oCBp5kNEAIQBQ"; // <GPGSID>
        public const string achievement_doing_well = "CgkI8oCBp5kNEAIQBw"; // <GPGSID>
        public const string achievement_invisable = "CgkI8oCBp5kNEAIQIQ"; // <GPGSID>
        public const string achievement_on_own_feet = "CgkI8oCBp5kNEAIQHw"; // <GPGSID>
        public const string achievement_shining = "CgkI8oCBp5kNEAIQGw"; // <GPGSID>

}

